### ISSUE TITLE
[ VideoDownloader][v1.3 ]The app crashes if I click on "WhatsApp Story Saver"

### ISSUE THREAD

**Issue by 44asad** [capturemathan/VideoDownloader#1]
### Expected behavior
I expected that the app would not crash when I click on WhatsApp Story saver.I believe the users should be able to press the WhatsApp story saver during that encryption process.

### Actual behavior:
The application is crash when I click WhatsApp Story Saver.

### How to reproduce:
* Download the app and open it
* Click  let's Download
* Click naw other option.
* not see bug
* Then click WhatsApp Story Saver.
* see bug

### Information
* App version:v1.3
* OS:Android 6.0.1
* Device:Samsung J5
### Recording Of The Bug

https://youtu.be/iMx1cEMmZio

### Logcat:
<pre><code>05-19 03:45:00.501  5461  5461 E AndroidRuntime: FATAL EXCEPTION: main
05-19 03:45:00.501  5461  5461 E AndroidRuntime: Process: com.allvideodownloader.socialmedia.videodownloader, PID: 5461
05-19 03:45:00.501  5461  5461 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.allvideodownloader.socialmedia.videodownloader/com.allvideodownloader.socialmedia.videodownloader.WhatsApp}: java.lang.NullPointerException: Attempt to read from null array
05-19 03:45:00.501  5461  5461 E AndroidRuntime:   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3256)
05-19 03:45:00.501  5461  5461 E AndroidRuntime:   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3352)
05-19 03:45:00.501  5461  5461 E AndroidRuntime:   at android.app.ActivityThread.access$1100(ActivityThread.java:223)
05-19 03:45:00.501  5461  5461 E AndroidRuntime:   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1797)
05-19 03:45:00.501  5461  5461 E AndroidRuntime:   at android.os.Handler.dispatchMessage(Handler.java:102)
05-19 03:45:00.501  5461  5461 E AndroidRuntime:   at android.os.Looper.loop(Looper.java:158)
05-19 03:45:00.501  5461  5461 E AndroidRuntime:   at android.app.ActivityThread.main(ActivityThread.java:7231)
05-19 03:45:00.501  5461  5461 E AndroidRuntime:   at java.lang.reflect.Method.invoke(Native Method)
05-19 03:45:00.501  5461  5461 E AndroidRuntime:   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
05-19 03:45:00.501  5461  5461 E AndroidRuntime:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
05-19 03:45:00.501  5461  5461 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to read from null array
05-19 03:45:00.501  5461  5461 E AndroidRuntime:   at com.allvideodownloader.socialmedia.videodownloader.WhatsApp.onCreate(WhatsApp.java:44)
05-19 03:45:00.501  5461  5461 E AndroidRuntime:   at android.app.Activity.performCreate(Activity.java:6877)
05-19 03:45:00.501  5461  5461 E AndroidRuntime:   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
05-19 03:45:00.501  5461  5461 E AndroidRuntime:   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3209)
05-19 03:45:00.501  5461  5461 E AndroidRuntime:   ... 9 more</code></pre>

**Comment by 44asad** [comment]
@capturemathan sir.

**Comment by capturemathan** [comment]
I'll check the same , thanks for the report !
