### ISSUE TITLE
Add support for Dark Mode

### ISSUE THREAD

**Issue by capturemathan** [capturemathan/VideoDownloader#10]
- [ ] Currently, the app supports only `Light mode`, have a toggle button to support `Dark mode` 🌑

**Comment by GowthamGoush** [comment]
Hello Mathan , I've added the dark mode but I couldn't find a room to place the toggle button. Shall I add this up in action bar ?

**Comment by capturemathan** [comment]
> Hello Mathan , I've added the dark mode but I couldn't find a room to place the toggle button. Shall I add this up in action bar ?

Yeah sure, you can do the same. And don't forget to add screenshots after finishing.
