### ISSUE TITLE
[ VideoDownloader][v1.3 ]The app crashes if I click on Facebook "Download In Standard defintion"

### ISSUE THREAD

**Issue by 44asad** [capturemathan/VideoDownloader#2]
### Expected behavior
I expected that the app would not crash when I click on Facebook "Download In Standard defintion"

### Actual behavior:
The application is crash when I click Facebook "Download In Standard defintion"

### How to reproduce:
* Download the app and open it
* Click  let's Download
* Click naw Facebook option.
* Paste video links
* Then click  "Download In Standard defintion"
* see bug

### Information
* App version:v1.3
* OS:Android 6.0.1
* Device:Samsung J5
### Recording Of The Bug:
https://youtu.be/7VpGrxTdyco

### Logcat:
<pre><code>05-19 03:48:28.821  5546  5546 E AndroidRuntime: FATAL EXCEPTION: main
05-19 03:48:28.821  5546  5546 E AndroidRuntime: Process: com.allvideodownloader.socialmedia.videodownloader, PID: 5546
05-19 03:48:28.821  5546  5546 E AndroidRuntime: java.lang.NullPointerException: uriString
05-19 03:48:28.821  5546  5546 E AndroidRuntime:   at android.net.Uri$StringUri.<init>(Uri.java:476)
05-19 03:48:28.821  5546  5546 E AndroidRuntime:   at android.net.Uri$StringUri.<init>(Uri.java:466)
05-19 03:48:28.821  5546  5546 E AndroidRuntime:   at android.net.Uri.parse(Uri.java:438)
05-19 03:48:28.821  5546  5546 E AndroidRuntime:   at com.allvideodownloader.socialmedia.videodownloader.DownloadActivity$Facebook$1.onClick(DownloadActivity.java:254)
05-19 03:48:28.821  5546  5546 E AndroidRuntime:   at android.view.View.performClick(View.java:5698)
05-19 03:48:28.821  5546  5546 E AndroidRuntime:   at android.widget.TextView.performClick(TextView.java:10908)
05-19 03:48:28.821  5546  5546 E AndroidRuntime:   at android.view.View$PerformClick.run(View.java:22565)
05-19 03:48:28.821  5546  5546 E AndroidRuntime:   at android.os.Handler.handleCallback(Handler.java:739)
05-19 03:48:28.821  5546  5546 E AndroidRuntime:   at android.os.Handler.dispatchMessage(Handler.java:95)
05-19 03:48:28.821  5546  5546 E AndroidRuntime:   at android.os.Looper.loop(Looper.java:158)
05-19 03:48:28.821  5546  5546 E AndroidRuntime:   at android.app.ActivityThread.main(ActivityThread.java:7231)
05-19 03:48:28.821  5546  5546 E AndroidRuntime:   at java.lang.reflect.Method.invoke(Native Method)
05-19 03:48:28.821  5546  5546 E AndroidRuntime:   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
05-19 03:48:28.821  5546  5546 E AndroidRuntime:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)</code></pre>

**Comment by 44asad** [comment]
@capturemathan sir

**Comment by capturemathan** [comment]
The application does'nt support any of the private Facebook videos.

**Comment by 44asad** [comment]
sir,
no,private Facebook video.its local facebook video.check its?

**Comment by capturemathan** [comment]
Send me the facebook video link.
