### ISSUE TITLE
App is stolen and being sold on Codecanyon

### ISSUE THREAD

**Issue by Aym9n** [capturemathan/VideoDownloader#7]
Loool someone is selling this app, he is doing same with other apps, you can appeal to Envato here is how: https://help.market.envato.com/hc/en-us/articles/202822720-How-to-submit-a-valid-DMCA-takedown-notice-in-relation-to-an-Author-s-item-on-Envato-Market

App: https://codecanyon.net/item/waf-video-downloader-of-facebook-whatsapp-and-instagram/24641016?s_rank=2

**Comment by capturemathan** [comment]
Thank you so much for reporting and the issue will be taken care 😉
